name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Publish Test Results
        if: always()
        uses: mikepenz/action-junit-report@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: "**/jest-github-actions-reporter.xml"
